nelmio_api_doc:
    documentation:
        info:
            title: SolarCentury Test Documentation
            description: Usefull documentation for test purposes
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/provider(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/provider(?!/doc$) # Accepts routes under /api except /api/doc
